# Generated by Django 2.0.6 on 2019-02-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('alcohol_percentage', models.IntegerField()),
                ('serving_glass', models.CharField(max_length=200)),
            ],
        ),
    ]
